CREATE DATABASE IF NOT EXISTS kame_house CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE kame_house;

CREATE TABLE IF NOT EXISTS players (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(24) NOT NULL UNIQUE,
    password VARCHAR(16) NOT NULL,
    money INT NOT NULL DEFAULT 500,
    admin_level INT NOT NULL DEFAULT 0,
    camionero_nivel INT NOT NULL DEFAULT 0,
    camionero_viajes INT NOT NULL DEFAULT 0,
    pizzero_nivel INT NOT NULL DEFAULT 0,
    pizzero_entregas INT NOT NULL DEFAULT 0,
    bank_money INT NOT NULL DEFAULT 0,
    semilla_hierba INT NOT NULL DEFAULT 0,
    semilla_flor INT NOT NULL DEFAULT 0,
    hierba INT NOT NULL DEFAULT 0,
    flor INT NOT NULL DEFAULT 0,
    tiempo_jugado_min INT NOT NULL DEFAULT 0,
    skin INT NOT NULL DEFAULT 229,
    pos_x FLOAT NOT NULL DEFAULT 2494.24,
    pos_y FLOAT NOT NULL DEFAULT -1671.19,
    pos_z FLOAT NOT NULL DEFAULT 13.33,
    version INT NOT NULL DEFAULT 4,
    madera INT NOT NULL DEFAULT 0,
    piedra INT NOT NULL DEFAULT 0,
    cobre INT NOT NULL DEFAULT 0,
    hierro_mineral INT NOT NULL DEFAULT 0,
    polvora INT NOT NULL DEFAULT 0,
    prepieza INT NOT NULL DEFAULT 0,
    carbon INT NOT NULL DEFAULT 0,
    tiene_mazo TINYINT(1) NOT NULL DEFAULT 0,
    mazo_durabilidad INT NOT NULL DEFAULT 0,
    armero_nivel INT NOT NULL DEFAULT 1,
    armero_exp INT NOT NULL DEFAULT 0,
    basurero_nivel INT NOT NULL DEFAULT 0,
    basurero_recorridos INT NOT NULL DEFAULT 0,
    bidon_gasolina INT NOT NULL DEFAULT 0,
    tiene_telefono TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
